### ISSUE TITLE
[NewsPublish] Don't publish command messages

### ISSUE THREAD

**Issue by zephyrkul** [SharkyTheKing/Sharky#66]
# Feature Request

#### What type of feature are you requesting:

- [ ] Cog
- [ ] Command
- [X] An enhancement to an existing cog or command.

#### Describe the feature:

Use `on_message_without_command` (or have an option for it) in NewsPublish so it doesn't publish command messages.
Sometimes my server uses `[p]embed event` in a server in order to announce an upcoming event, but we don't want that command message itself to be announced, only the bot's response.

Also, unrelated, but it's worth noting: Manage Messages is only needed for publishing others' messages. The bot doesn't need that permission to publish its own message.
It may also be worth catching `discord.Forbidden` in the event itself (or checking for permissions before publishing) in case permissions change in the announcement channel.

**Comment by SharkyTheKing** [comment]
You know, I completely didn't take into account people may use bot commands in the channel for reasons. I'll change this. 

Hmm, the only issue is. I have to use asyncio.wait_for which I need because discord doesn't send you any notification until AFTER the cooldown is up for the ratelimit, which defeats the purpose of alerting the discord staff that the publish failed.

If you have any suggestions on to combating that, let me know! I'll think of some stuff if I can get that working for discord.forbidden.

**Comment by zephyrkul** [comment]
> Hmm, the only issue is. I have to use asyncio.wait_for which I need because discord doesn't send you any notification until AFTER the cooldown is up for the ratelimit, which defeats the purpose of alerting the discord staff that the publish failed.

Sorry, not sure what this part has to do with this issue: I made no comment on the use of wait_for, since that is currently the best method to deal with saturating the rate limit. May I ask where this came from?

**Comment by SharkyTheKing** [comment]
Ah, I realize I read your message regarding manage_message wrong. 

My bad.

**Comment by zephyrkul** [comment]
Thanks for the update. I'd like to note that the below minor issues are still present, though it's not particularly relevant to the main topic of this issue. Would you prefer that I file a separate issue to for this?

> Also, unrelated, but it's worth noting: Manage Messages is only needed for publishing others' messages. The bot doesn't need that permission to publish its own message.
> It may also be worth catching `discord.Forbidden` in the event itself (or checking for permissions before publishing) in case permissions change in the announcement channel.

**Comment by SharkyTheKing** [comment]
Nope you're fine, you can if you want! I have a plan on how to account for that when I'm adding another feature.

Going to be checking who posted the message, if it's not from the bot, try to check perms, if it's unable to publish then I'll return a message to the alert-channel that it can't publish, if the alert-channel isn't set then I'll have it attempt to DM the person who made the message.
